using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using System.Linq;

namespace Content.Client.Implants.UI;

[GenerateTypedNameReferences]
public sealed partial class DeimplantChoiceWindow : FancyWindow
{
    public Action<string?>? OnImplantChange;

    private Dictionary<string, string> _implants = new();

    private string? _chosenImplant;
    private bool _hasStoredImplant;
    private bool _blocked;

    public DeimplantChoiceWindow()
    {
        RobustXamlLoader.Load(this);

        ImplantSelector.OnItemSelected += args =>
        {
            if (_blocked || _hasStoredImplant)
                return;

            OnImplantChange?.Invoke(_implants.ElementAt(args.Id).Key);
            ImplantSelector.SelectId(args.Id);
        };
    }

    public void UpdateImplantList(Dictionary<string, string> implants)
    {
        _implants = implants;
        int i = 0;
        ImplantSelector.Clear();
        foreach (var implantDict in _implants)
        {
            ImplantSelector.AddItem(implantDict.Value, i);
            i++;
        }
    }

    public void UpdateState(string? implant, bool hasStoredImplant, bool blocked)
    {
        _chosenImplant = implant;
        _hasStoredImplant = hasStoredImplant;
        _blocked = blocked;

        if (blocked || hasStoredImplant)
        {
            ImplantSelector.Disabled = true;
            StatusLabel.SetMarkup(Loc.GetString("implanter-implant-stored-blocked"));
            ConfirmButton.Visible = false;
        }
        else
        {
            ImplantSelector.Disabled = false;
            StatusLabel.SetMarkup("");
            ConfirmButton.Visible = true;
        }

        for (int id = 0; id < ImplantSelector.ItemCount; id++)
        {
            if (_implants.ElementAt(id).Key.Equals(_chosenImplant))
            {
                ImplantSelector.SelectId(id);
                break;
            }
        }
    }
}
